Repository Jeju-Month/jejumonth-frontend, pull requests merged in 2025-01, with the labels that each got.

#28 Feature/timer and calendar
  package.json
  src/App.jsx
  src/layouts/PlanLayout.jsx
  src/pages/AddPlanPage/components/ButtonList.jsx
  src/pages/AddPlanPage/components/RegisterDayAndTime.jsx
  src/pages/AddPlanPage/components/WeekCalendar.jsx
  src/pages/AddPlanPage/index.jsx
  src/pages/CommunityPage/index.jsx
  src/pages/MyTripPage/index.jsx
  src/pages/index.jsx
  src/routes/router.jsx
  src/utils/dateFormat.js
  src/utils/hourFormat.js
  yarn.lock
Labels: 🚀기능

#33 [FEAT] 토스터 추가 및 UI 변경
  src/pages/AddPlanPage/components/ButtonList.jsx
  src/pages/AddPlanPage/components/RegisterDayAndTime.jsx
  src/pages/AddPlanPage/components/WeekCalendar.jsx
  src/utils/hourFormat.js
Labels: 🔧리팩터링

#44 [FEAT] 유저 관련 수파베이스 API 구현
  src/apis/supabaseApi.js
  src/pages/AddTripPage/index.jsx
Labels: 우선순위상, 🚀기능

#49 [FEAT] 유저정보수정 및 프로필 업데이트 기능 구현 완료
  package.json
  public/icons/image-file.svg
  public/images/default-profile.png
  public/images/image.js
  src/apis/user.js
  src/components/common/Form/index.jsx
  src/components/common/FormInput/FileInput.jsx
  src/components/common/FormInput/TextInput.jsx
  src/pages/MyPage/components/main/updateUserProfile/UpdateUserSection.jsx
  src/pages/MyPage/components/main/updateUserProfile/userUpdateInputs.js
  src/routes/router.jsx
  vite.config.js
  yarn.lock
Labels: 우선순위상, 🚀기능

#51 fix : 충돌과정에서 누락된 코드 복원
  src/pages/AddPlanPage/index.jsx
Labels: 🐛버그
